namespace Emby.Sso.Protocol
{
    /// <summary>
    /// The vendor's licence-signing PUBLIC keys, as JWKs, compiled into the
    /// plugin. A licence is accepted if it was signed by ONE OF THESE, and by
    /// nothing else.
    ///
    /// A SET, NOT A KEY, AND THAT IS THE POINT. A build that trusts exactly one
    /// key cannot survive that key leaking: the only remedy is a new keypair and
    /// a new build, which stops every licence in the field at the same moment,
    /// including the ones belonging to customers who did nothing wrong. With a
    /// set, the new key is added and shipped while the old one is still trusted,
    /// customers are reissued at their own pace, and the old key is dropped in a
    /// later release. Rotation becomes a release rather than an outage.
    ///
    ///   * TO ROTATE: keep the entry that is here, add the new one, ship. Reissue
    ///     customers onto the new key. Delete the old entry in a later release,
    ///     once no licence signed by it is still valid.
    ///   * TO REVOKE, because a key leaked: DELETE its entry and ship
    ///     immediately. There is no revocation list and there is no callback -
    ///     the check is offline - so a key is revoked by not being here any more.
    ///     Every licence it signed stops working, which is exactly what a leaked
    ///     key requires, and is why rotating early is worth the trouble.
    ///
    /// Each licence names the key that signed it in its `kid` header, and the
    /// name is derived from the key itself (see the issuing tool's `keygen`
    /// output), so nothing has to keep a registry of which name meant which key.
    ///
    /// HOW TO ADD ONE. Run the issuing tool on a machine that is not this
    /// repository's working tree and is not a server:
    ///
    ///     dotnet run --project tools/Emby.Sso.LicenceTool -- keygen --out ~/emby-sso-licence
    ///
    /// It writes the PRIVATE key to a file and prints the PUBLIC JWK and its key
    /// id. Paste that one line into the array below and rebuild. The private key
    /// never enters this repository and never goes on a server - the licence
    /// service does not sign anything and has no key to steal. See
    /// tools/Emby.Sso.LicenceTool/README.md.
    ///
    /// AN EMPTY SET MEANS EVERY SSO SIGN-IN IS REFUSED. That is deliberate and
    /// is the fail-closed direction: a build with no key cannot verify any
    /// licence, so it cannot honestly accept one. The server log says exactly
    /// that. Emby's own local accounts are unaffected - they are authenticated
    /// by Emby's own provider, not by this plugin - so an operator is never
    /// locked out of their own server by it.
    ///
    /// These are build-time constants rather than settings on purpose. A public
    /// key an operator could edit is a public key an operator could replace with
    /// their own, and then mint their own licences.
    ///
    /// It is still, of course, only a constant inside a .NET assembly that
    /// anyone can decompile and rebuild. See <see cref="LicenceCheck"/> for what
    /// this scheme does and does not achieve.
    /// </summary>
    internal static class LicencePublicKey
    {
        /// <summary>
        /// Every key a licence may have been signed by. Order does not matter;
        /// the licence's `kid` picks one, and a licence with an unknown `kid`
        /// falls back to being tried against all of them, so a key added here
        /// works for licences issued before this build existed.
        /// </summary>
        public static readonly string[] TrustedJwks =
        {
            // Key id 71870a0bad21ceb2. The vendor's own key, generated by them on
            // a machine of their choosing, 2026-09-01. Its private half has never
            // been on a server and has never been in this repository - only
            // `licencetool sign`, run by hand, ever loads it.
            //
            // TWO KEYS HAVE BEEN RETIRED, and neither is in this array, which is
            // what revoking one means: a licence signed by a key that is not here
            // fails its signature check exactly like a forgery.
            //
            //   * the original key, which had been loaded at startup by the
            //     internet-facing licence service AND pasted into a chat window;
            //   * an interim key generated during that repair, whose private half
            //     lived on a development workspace the vendor does not control.
            //
            // Nothing signed by either validates. See docs/site/key-rotation.md.
            "{\"kty\":\"RSA\",\"n\":\"mLRpkFw1hHejXBkIJxaX2ORwU-xa9oEBObeIaAppbb63l6rjoWaFA-ynuwscFEyhUjVh9t9iGvn_BS9hwu0WdXBSLCo3kELE5C4GmwENGmugYoksqJ6aZSqSqTFSalQ62XIsAcbDKU-qM4iH9d7tdWMvDSJo3h3XWCeDWxi-cJbwLGnidVvaaG3Jw2xhrGra631TlzEPHPjRGgaAlQG9Yg0n2iwuSjqVlgfvghwHuduUiDd461wHTEHkpk__ZVCug_cv6PfK49avq4DmIZbeRFvKevXZ-FnpUqdJsukQVgTfcpEOexM_VrnCDghXlohk83tgPWYdQ2VgHGh3LPk7EZoMJ0uoAsR7glSgSBWs0gXPMkytWVHDpP_J4lkrZydDPpB10MH3MLiFvLBd-N92MXDDEEG6yc72MQhEoekdfqlFh243QJw6f01DW8IGklF44Pl2jZ_PVCaJy2pCdYj19h9pglhvzGuBJPvEiu5yihWVlpW9Yf5Aty4M9FBiayYP\",\"e\":\"AQAB\"}",
        };
    }
}
