namespace Emby.Sso.Protocol
{
    /// <summary>
    /// The vendor's PLUGIN RELEASE signing public key, compiled into the plugin.
    ///
    /// A DIFFERENT KEY FROM THE LICENCE KEY, AND THAT IS THE WHOLE POINT. This
    /// one authorises CODE: a build signed by it will be downloaded and written
    /// into Emby's plugins directory, and then executed. The licence key
    /// authorises an assertion about a licence, which costs the vendor a sale
    /// when it is abused. These are not the same risk and must not share a key.
    ///
    /// Concretely: the licence key lives on the licence service, because the
    /// vendor chose instant self-service activation and that requires it. If
    /// that key also signed releases, anyone who broke into that service could
    /// push a backdoored DLL to every customer's media server. This key lives on
    /// the vendor's own machine, is never on a server, and is never in a CI
    /// variable - so a total compromise of the licence service still cannot ship
    /// code.
    ///
    /// EMPTY MEANS THE UPDATE FEATURE DOES NOT EXIST. That is the fail-closed
    /// direction and it is deliberate: a build with no release key cannot verify
    /// a manifest, so it must never install anything. Everything else about the
    /// plugin works exactly as before.
    ///
    /// A build-time constant rather than a setting, for a stronger reason than
    /// the licence key: a release key an operator could edit is a way to make
    /// somebody's server install a DLL of your choosing.
    /// </summary>
    internal static class ReleasePublicKey
    {
        /// <summary>
        /// Key id 56468f4a15dd461e. Generated by the vendor on their own
        /// machine, 2026-09-02, for signing plugin releases and nothing else.
        ///
        /// It has never been on a server, is not in this repository, and is not
        /// in CI. See docs/site/updating.md.
        /// </summary>
        public static readonly string[] TrustedJwks =
        {
            "{\"kty\":\"RSA\",\"n\":\"ljU246bORwPSCWXKVtlLMoYc-L3hXRU1SD8caZTXmBODjKfrkI9TeY8qW1B3wJGSyUWkWa23Tj6uG0GQxr-WlYs2k4D2TXAP73EXTBGSvQOzHi6MEUprnv49u1Q2bdeX4rYvUScVrMDbEz042XlHsNujlSeLT95lIOifBlRRBUzScQ-sb_L4VssK0gy11FZFfzXa238K4te0HSqCac2ZUhjBmTX1O1NWhrFLwNdRq9xeH80X-qJGhacpg8IUkEKCRlVFLx_gv1xDugSr9mBXiIbnB7mcgD9wzd7ZDgtodHnSlUE1l6A509cGwFPMHnG5Ys2erLu-f2EHgO-AhDLkSsavrFKvJZZtV42cfFKeihThOB-IpDeAGc7e4oOxkAZO8MdDyJzI7RlWjpYrPZGZafzW_yVJoZLI1ynmS1G81xDQ5DP7qBJKojlbYZ15bPgyOFZmgoUnvL3pDj5CF2GLk0TYUmcwP1csTRwFZQRLlZbUJ4D66eKJEnpDUIGMdXnP\",\"e\":\"AQAB\"}",
        };
    }
}
