#!/bin/sh
# Publishes docs/site/ into this project's GitLab wiki.
#
# WHY A WIKI AND NOT ONLY PAGES. This project is private, and GitLab Pages for
# a private project is behind the same sign-in as everything else - so it was
# never the "anyone can read it" that a documentation site usually implies. The
# wiki is where the people who already have access look, it is editable in the
# browser when something is wrong, and it needs no build. The Pages job stays;
# both are generated from docs/site/, so there is one source and they cannot
# disagree.
#
# ONE SOURCE, ONE DIRECTION. This script overwrites the wiki from the
# repository, every time. Anything typed into the wiki by hand is lost on the
# next push to the default branch. That is deliberate - two editable copies of
# the same page is how documentation starts lying - and it is said again at the
# top of every page it writes.
#
# WHAT IT NEEDS: WIKI_TOKEN, a project access token (or personal access token)
# with `write_repository` scope, set as a MASKED, PROTECTED CI/CD variable.
# CI_JOB_TOKEN cannot push to a wiki - GitLab does not grant it that - so there
# is no way to do this without a stored credential. Scope it to this project
# only, and give it Developer, not Maintainer.
set -eu

if [ -z "${WIKI_TOKEN:-}" ]; then
    echo "publish-wiki: WIKI_TOKEN is not set." >&2
    echo "  Create a project access token with the write_repository scope" >&2
    echo "  (Settings -> Access tokens), then add it as a masked, protected" >&2
    echo "  CI/CD variable named WIKI_TOKEN. CI_JOB_TOKEN cannot push to a wiki." >&2
    exit 1
fi

SOURCE="${1:-docs/site}"
WORK="$(mktemp -d)"

# The credential goes in a header, never in the remote URL: a URL with a token
# in it ends up in .git/config, in the job log on any error git prints, and in
# the output of `git remote -v`.
AUTH="$(printf 'gitlab-ci-token:%s' "$WIKI_TOKEN" | base64 | tr -d '\n')"

git -c http.extraheader="Authorization: Basic $AUTH" \
    clone --depth 1 "$CI_SERVER_URL/$CI_PROJECT_PATH.wiki.git" "$WORK/wiki" 2>/dev/null \
    || git -c http.extraheader="Authorization: Basic $AUTH" \
       clone "$CI_SERVER_URL/$CI_PROJECT_PATH.wiki.git" "$WORK/wiki"

# Everything this script wrote last time goes, so a page deleted from the
# repository is deleted from the wiki. Anything else in the wiki - a page
# somebody made by hand that is not one of ours - is left alone.
find "$WORK/wiki" -maxdepth 1 -name '*.md' ! -name '.*' -delete

for file in "$SOURCE"/*.md; do
    name="$(basename "$file")"

    # GitLab's wiki landing page is `home`. Everything else keeps its name, so
    # the relative links between pages keep working without rewriting them.
    case "$name" in
        index.md) target="home.md" ;;
        *) target="$name" ;;
    esac

    {
        echo "<!-- Generated from docs/site/$name by ci/publish-wiki.sh. -->"
        echo "<!-- Edits made here are overwritten on the next push to the default branch. -->"
        echo
        # Two passes:
        #
        #   * ci/wiki-markdown.awk turns Material admonitions into blockquotes.
        #     Without it GitLab renders their indented bodies as CODE BLOCKS,
        #     so the loudest warnings in this documentation - the ones about
        #     locking every user out - would arrive looking like sample output.
        #   * sed rewrites the links. index.md is the only name that changes,
        #     because GitLab's landing page is `home`; every other page keeps
        #     its name and only loses the .md, which is how wiki links work.
        awk -f ci/wiki-markdown.awk "$file" \
            | sed -e 's#(index\.md)#(home)#g' \
                  -e 's#(index\.md\##(home\##g' \
                  -e 's#\.md)#)#g' \
                  -e 's#\.md\##\##g' 
    } > "$WORK/wiki/$target"
done

cd "$WORK/wiki"

git config user.email "ci@$CI_SERVER_HOST"
git config user.name "Documentation from CI"

git add -A

if git diff --cached --quiet; then
    echo "publish-wiki: the wiki already matches docs/site. Nothing to push."
    exit 0
fi

git commit -m "docs: sync from $CI_COMMIT_SHORT_SHA

Generated by ci/publish-wiki.sh from docs/site/ on $CI_COMMIT_REF_NAME.
Edit the files in the repository, not here."

git -c http.extraheader="Authorization: Basic $AUTH" push origin HEAD:master

echo "publish-wiki: pushed $(ls -1 ./*.md | wc -l) page(s) to $CI_PROJECT_URL/-/wikis/home"
